export const data = {
  request: {
    type: "City",
    query: "New York, United States of America",
    language: "en",
    unit: "m",
  },
  location: {
    name: "New York",
    country: "United States of America",
    region: "New York",
    lat: "40.714",
    lon: "-74.006",
    timezone_id: "America/New_York",
    localtime: "2023-07-17 04:54",
    localtime_epoch: 1689569640,
    utc_offset: "-4.0",
  },
  current: {
    observation_time: "08:54 AM",
    temperature: 24,
    weather_code: 116,
    weather_icons: [
      "https://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png",
    ],
    weather_descriptions: ["Partly cloudy"],
    wind_speed: 4,
    wind_degree: 319,
    wind_dir: "NW",
    pressure: 1012,
    precip: 0,
    humidity: 94,
    cloudcover: 50,
    feelslike: 27,
    uv_index: 1,
    visibility: 16,
    is_day: "no",
  },
};
